BACKUPBOX_SIGNALS = [
    {
        "id": 10001,
        "display_name": "Status",
        "translation_key": "status",
        "name": "Status",
        "unit": None,
        "device_class": "enum",
    },
    {
        "id": 10007,
        "display_name": "Grid A Phase Voltage",
        "translation_key": "grid_a_phase_voltage",
        "name": "Grid A phase voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10008,
        "display_name": "Grid B Phase Voltage",
        "translation_key": "grid_b_phase_voltage",
        "name": "Grid B phase voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10009,
        "display_name": "Grid C Phase Voltage",
        "translation_key": "grid_c_phase_voltage",
        "name": "Grid C phase voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10063,
        "display_name": "Phase A Voltage of Backup Load",
        "translation_key": "phase_a_voltage_of_backup_load",
        "name": "Phase A voltage of backup load",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10064,
        "display_name": "Phase B Voltage of Backup Load",
        "translation_key": "phase_b_voltage_of_backup_load",
        "name": "Phase B voltage of backup load",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10065,
        "display_name": "Phase C Voltage of Backup Load",
        "translation_key": "phase_c_voltage_of_backup_load",
        "name": "Phase C voltage of backup load",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10061,
        "display_name": "Internal Ambient Temperature",
        "translation_key": "internal_ambient_temperature",
        "name": "Internal ambient temperature",
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
    },
]
