EMMA_SIGNALS = [
    {
        "id": 11115,
        "display_name": "Forward Active Energy",
        "translation_key": "forward_active_energy",
        "name": "Forward active energy",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "id": 11116,
        "display_name": "Reverse Active Energy",
        "translation_key": "reverse_active_energy",
        "name": "Reverse active energy",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "id": 11208,
        "display_name": "Reactive Power",
        "translation_key": "reactive_power",
        "name": "Reactive power",
        "unit": "kvar",
        "device_class": "reactive_power",
        "state_class": "measurement",
    },
    {
        "id": 11207,
        "display_name": "Active Power",
        "translation_key": "active_power",
        "name": "Active power",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 10014,
        "display_name": "Power Factor",
        "translation_key": "power_factor",
        "name": "Power factor",
        "unit": None,
        "device_class": "power_factor",
        "state_class": "measurement",
    },
    {
        "id": 11209,
        "display_name": "Active Power Pa",
        "translation_key": "active_power_pa",
        "name": "Active power Pa",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11210,
        "display_name": "Active Power Pb",
        "translation_key": "active_power_pb",
        "name": "Active power Pb",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11211,
        "display_name": "Active Power Pc",
        "translation_key": "active_power_pc",
        "name": "Active power Pc",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11204,
        "display_name": "Phase A Voltage",
        "translation_key": "phase_a_voltage",
        "name": "Phase A voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11205,
        "display_name": "Phase B Voltage",
        "translation_key": "phase_b_voltage",
        "name": "Phase B voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11206,
        "display_name": "Phase C Voltage",
        "translation_key": "phase_c_voltage",
        "name": "Phase C voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10009,
        "display_name": "Phase A Current",
        "translation_key": "phase_a_current",
        "name": "Phase A current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 10010,
        "display_name": "Phase B Current",
        "translation_key": "phase_b_current",
        "name": "Phase B current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 10011,
        "display_name": "Phase C Current",
        "translation_key": "phase_c_current",
        "name": "Phase C current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
]
