POWER_SENSOR_SIGNALS = [
    {
        "id": 10001,
        "display_name": "Meter Status",
        "translation_key": "meter_status",
        "name": "Meter status",
        "unit": None,
        "device_class": "enum",
    },
    {
        "id": 10008,
        "display_name": "Positive Active Energy",
        "translation_key": "positive_active_energy",
        "name": "Positive active energy",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "id": 10009,
        "display_name": "Phase A Current",
        "translation_key": "negative_active_energy",
        "name": "Negative active energy",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "id": 10005,
        "display_name": "Reactive Power",
        "translation_key": "reactive_power",
        "name": "Reactive power",
        "unit": "var",
        "device_class": "reactive_power",
        "state_class": "measurement",
    },
    {
        "id": 10004,
        "display_name": "Active Power",
        "translation_key": "active_power",
        "name": "Active power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 10006,
        "display_name": "Power Factor",
        "translation_key": "power_factor",
        "name": "Power factor",
        "unit": None,
        "device_class": "power_factor",
        "state_class": "measurement",
    },
    {
        "id": 10019,
        "display_name": "Phase A Active Power",
        "translation_key": "phase_a_active_power",
        "name": "Phase A active power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 10020,
        "display_name": "Phase B Active Power",
        "translation_key": "phase_b_active_power",
        "name": "Phase B active power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 10021,
        "display_name": "Phase C Active Power",
        "translation_key": "phase_c_active_power",
        "name": "Phase C active power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 10002,
        "display_name": "Phase A Voltage",
        "translation_key": "phase_a_voltage",
        "name": "Phase A voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10010,
        "display_name": "Phase B Current",
        "translation_key": "phase_b_voltage",
        "name": "Phase B voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10011,
        "display_name": "Phase C Current",
        "translation_key": "phase_c_voltage",
        "name": "Phase C voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10003,
        "display_name": "Phase A Current",
        "translation_key": "phase_a_current",
        "name": "Phase A current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 10012,
        "display_name": "Phase B Current",
        "translation_key": "phase_b_current",
        "name": "Phase B current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 10013,
        "display_name": "Phase C Current",
        "translation_key": "phase_c_current",
        "name": "Phase C current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 10007,
        "display_name": "Grid Frequency",
        "translation_key": "grid_frequency",
        "name": "Grid frequency",
        "unit": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
    },
]

EMMA_A02_SIGNALS = [
    {
        "id": 11115,
        "display_name": "Forward Active Energy",
        "translation_key": "forward_active_energy",
        "name": "Forward active energy",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "id": 11116,
        "display_name": "Reverse Active Energy",
        "translation_key": "reverse_active_energy",
        "name": "Reverse active energy",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "id": 11208,
        "display_name": "Reactive Power",
        "translation_key": "reactive_power",
        "name": "Reactive power",
        "unit": "kvar",
        "device_class": "reactive_power",
        "state_class": "measurement",
    },
    {
        "id": 11207,
        "display_name": "Active Power",
        "translation_key": "active_power",
        "name": "Active power",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 10014,
        "display_name": "Power Factor",
        "translation_key": "power_factor",
        "name": "Power factor",
        "unit": None,
        "device_class": "power_factor",
        "state_class": "measurement",
    },
    {
        "id": 11209,
        "display_name": "Phase A Active Power",
        "translation_key": "phase_a_active_power",
        "name": "Active power Pa",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11210,
        "display_name": "Phase B Active Power",
        "translation_key": "phase_b_active_power",
        "name": "Active power Pb",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11211,
        "display_name": "Phase C Active Power",
        "translation_key": "phase_c_active_power",
        "name": "Active power Pc",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11204,
        "display_name": "Phase A Voltage",
        "translation_key": "phase_a_voltage",
        "name": "Phase A voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11205,
        "display_name": "Phase B Voltage",
        "translation_key": "phase_b_voltage",
        "name": "Phase B voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11206,
        "display_name": "Phase C Voltage",
        "translation_key": "phase_c_voltage",
        "name": "Phase C voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10009,
        "translation_key": "phase_a_current",
        "name": "Phase A current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 10010,
        "translation_key": "phase_b_current",
        "name": "Phase B current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 10011,
        "translation_key": "phase_c_current",
        "name": "Phase C current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 230700283,
        "display_name": "RS485-2 Port Mode",
        "translation_key": "r_s485_2_port_mode",
        "name": "RS485-2 port mode",
        "unit": None,
        "device_class": "enum",
    },
    {
        "id": 15101,
        "display_name": "WiFi Signal Strength",
        "translation_key": "wi_fi_signal_strength",
        "name": "WiFi Signal strength",
        "unit": "dBm",
        "device_class": "signal_strength",
        "state_class": "measurement",
    },
    {
        "id": 15102,
        "display_name": "Signal Strength",
        "translation_key": "signal_strength",
        "name": "Signal strength",
        "unit": "dBm",
        "device_class": "signal_strength",
        "state_class": "measurement",
    },
]

DTSU666_FE_SIGNALS = [
    {
        "id": 2101249,
        "display_name": "Communication Status",
        "translation_key": "communication_status",
        "name": "Communication Status",
        "unit": None,
        "device_class": "enum",
    },
    {
        "id": 2101252,
        "display_name": "AB Line Voltage",
        "translation_key": "ab_line_voltage",
        "name": "AB line voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 2101253,
        "display_name": "BC Line Voltage",
        "translation_key": "bc_line_voltage",
        "name": "BC line voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 2101254,
        "display_name": "CA Line Voltage",
        "translation_key": "ca_line_voltage",
        "name": "CA line voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 2101256,
        "display_name": "Phase A Voltage",
        "translation_key": "phase_a_voltage",
        "name": "Phase A voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 2101257,
        "display_name": "Phase B Voltage",
        "translation_key": "phase_b_voltage",
        "name": "Phase B voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 2101264,
        "display_name": "Phase C Voltage",
        "translation_key": "phase_c_voltage",
        "name": "Phase C voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 2101268,
        "display_name": "Phase A Current",
        "translation_key": "phase_a_current",
        "name": "Phase A current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 2101269,
        "display_name": "Phase B Current",
        "translation_key": "phase_b_current",
        "name": "Phase B current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 2101270,
        "display_name": "Phase C Current",
        "translation_key": "phase_c_current",
        "name": "Phase C current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 2101271,
        "display_name": "Active Power",
        "translation_key": "active_power",
        "name": "Active power",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 2101272,
        "display_name": "Reactive Power",
        "translation_key": "reactive_power",
        "name": "Reactive power",
        "unit": "kVar",
        "device_class": "reactive_power",
        "state_class": "measurement",
    },
    {
        "id": 2101280,
        "display_name": "Power Factor",
        "translation_key": "power_factor",
        "name": "Power factor",
        "unit": None,
        "device_class": "power_factor",
        "state_class": "measurement",
    },
    {
        "id": 2101281,
        "display_name": "Phase A Active Power",
        "translation_key": "phase_a_active_power",
        "name": "Phase A active power",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 2101282,
        "display_name": "Phase B Active Power",
        "translation_key": "phase_b_active_power",
        "name": "Phase B active power",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 2101283,
        "display_name": "Phase C Active Power",
        "translation_key": "phase_c_active_power",
        "name": "Phase C active power",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 2101600,
        "display_name": "iAcMeter",
        "translation_key": "i_ac_meter",
        "name": "iAcMeter",
        "unit": None,
        "device_class": "enum",
    },
    {
        "id": 2101601,
        "display_name": "iAcMeter IP",
        "translation_key": "i_ac_meter_ip",
        "name": "iAcMeter",
        "unit": None,
        "device_class": "enum",
    },
    {
        "id": 2101602,
        "display_name": "Comm Status",
        "translation_key": "comm_status",
        "name": "Comm Status",
        "unit": None,
        "device_class": "enum",
    },
    {
        "id": 2101605,
        "display_name": "iAcMeter Mode",
        "translation_key": "i_ac_meter_mode",
        "name": "iAcMeter",
        "unit": None,
        "device_class": "enum",
    },
    {
        "id": 2101606,
        "display_name": "Meter Data Source",
        "translation_key": "meter_data_source",
        "name": "Meter Data Source",
        "unit": None,
        "device_class": "enum",
    },
]
