INVERTER_SIGNALS = [
    {
        "id": 10025,
        "display_name": "Status",
        "translation_key": "status",
        "name": "Inverter status",
        "device_class": "enum",
    },
    {
        "id": 10020,
        "display_name": "Power Factor",
        "translation_key": "power_factor",
        "name": "Power factor",
        "unit": None,
        "device_class": "power_factor",
        "state_class": "measurement",
    },
    {
        "id": 21029,
        "display_name": "Output Mode",
        "translation_key": "output_mode",
        "name": "Output mode",
        "device_class": "enum",
    },
    {
        "id": 10027,
        "display_name": "Last Startup Time",
        "translation_key": "last_startup_time",
        "name": "Inverter startup time",
        "device_class": "enum",
    },
    {
        "id": 10028,
        "display_name": "Last Shutdown Time",
        "translation_key": "last_shutdown_time",
        "name": "Inverter shutdown time",
        "device_class": "enum",
    },
    {
        "id": 10032,
        "display_name": "Daily Energy",
        "translation_key": "daily_energy",
        "name": "Daily energy",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "id": 10029,
        "display_name": "Total Energy Produced",
        "translation_key": "total_energy_produced",
        "name": "Cumulative energy",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "id": 10018,
        "display_name": "Current Active Power",
        "translation_key": "current_active_power",
        "name": "Active power",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 10019,
        "display_name": "Reactive Power",
        "translation_key": "reactive_power",
        "name": "Output reactive power",
        "unit": "kvar",
        "device_class": "reactive_power",
        "state_class": "measurement",
    },
    {
        "id": 10006,
        "display_name": "Rated Power",
        "translation_key": "rated_power",
        "name": "Inverter rated power",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 10021,
        "display_name": "Grid Frequency",
        "translation_key": "grid_frequency",
        "name": "Grid frequency",
        "unit": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    {
        "id": 10014,
        "display_name": "Phase A Current",
        "translation_key": "phase_a_current",
        "name": "Grid phase A current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 10015,
        "display_name": "Phase B Current",
        "translation_key": "phase_b_current",
        "name": "Grid phase B current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 10016,
        "display_name": "Phase C Current",
        "translation_key": "phase_c_current",
        "name": "Grid phase C current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 10011,
        "display_name": "Phase A Voltage",
        "translation_key": "phase_a_voltage",
        "name": "Phase A voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10008,
        "display_name": "Phase A Voltage",
        "translation_key": "phase_a_voltage",
        "name": "Grid voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10012,
        "display_name": "Phase B Voltage",
        "translation_key": "phase_b_voltage",
        "name": "Phase B voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10013,
        "display_name": "Phase C Voltage",
        "translation_key": "phase_c_voltage",
        "name": "Phase C voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 10023,
        "display_name": "Temperature",
        "translation_key": "temperature",
        "name": "Internal temperature",
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    {
        "id": 10024,
        "display_name": "Insulation Resistance",
        "translation_key": "insulation_resistance",
        "name": "Insulation resistance",
        "unit": "MΩ",
    },
]

PV_SIGNALS = [
    {
        "id": 11001,
        "display_name": "[PV 1] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11002,
        "display_name": "[PV 1] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11003,
        "display_name": "[PV 1] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11004,
        "display_name": "[PV 2] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11005,
        "display_name": "[PV 2] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11006,
        "display_name": "[PV 2] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11007,
        "display_name": "[PV 3] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11008,
        "display_name": "[PV 3] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11009,
        "display_name": "[PV 3] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11010,
        "display_name": "[PV 4] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11011,
        "display_name": "[PV 4] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11012,
        "display_name": "[PV 4] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11013,
        "display_name": "[PV 5] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11014,
        "display_name": "[PV 5] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11015,
        "display_name": "[PV 5] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11016,
        "display_name": "[PV 6] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11017,
        "display_name": "[PV 6] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11018,
        "display_name": "[PV 6] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11019,
        "display_name": "[PV 7] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11020,
        "display_name": "[PV 7] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11021,
        "display_name": "[PV 7] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11022,
        "display_name": "[PV 8] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11023,
        "display_name": "[PV 8] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11024,
        "display_name": "[PV 8] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11025,
        "display_name": "[PV 9] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11026,
        "display_name": "[PV 9] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11027,
        "display_name": "[PV 9] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11028,
        "display_name": "[PV 10] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11029,
        "display_name": "[PV 10] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11030,
        "display_name": "[PV 10] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11031,
        "display_name": "[PV 11] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11032,
        "display_name": "[PV 11] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11033,
        "display_name": "[PV 11] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11034,
        "display_name": "[PV 12] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11035,
        "display_name": "[PV 12] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11036,
        "display_name": "[PV 12] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11037,
        "display_name": "[PV 13] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11038,
        "display_name": "[PV 13] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11039,
        "display_name": "[PV 13] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11040,
        "display_name": "[PV 14] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11041,
        "display_name": "[PV 14] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11042,
        "display_name": "[PV 14] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11043,
        "display_name": "[PV 15] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11044,
        "display_name": "[PV 15] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11045,
        "display_name": "[PV 15] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11046,
        "display_name": "[PV 16] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11047,
        "display_name": "[PV 16] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11048,
        "display_name": "[PV 16] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11049,
        "display_name": "[PV 17] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11050,
        "display_name": "[PV 17] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11051,
        "display_name": "[PV 17] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11052,
        "display_name": "[PV 18] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11053,
        "display_name": "[PV 18] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11054,
        "display_name": "[PV 18] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11055,
        "display_name": "[PV 19] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11056,
        "display_name": "[PV 19] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11057,
        "display_name": "[PV 19] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 11058,
        "display_name": "[PV 20] Input Voltage",
        "translation_key": "pv_input_voltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "id": 11059,
        "display_name": "[PV 20] Input Current",
        "translation_key": "pv_input_current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 11060,
        "display_name": "[PV 20] Input Power",
        "translation_key": "pv_input_power",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
]

OPTIMIZER_METRICS = [
    {
        "translation_key": "opt_output_power",
        "name": "outputPower",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "translation_key": "opt_total_energy",
        "name": "totalEnergy",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total",
    },
    {
        "translation_key": "opt_input_voltage",
        "name": "inputVoltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "translation_key": "opt_running_status",
        "name": "runningStatus",
        "unit": None,
        "device_class": None,
        "state_class": None,
    },
    {
        "translation_key": "opt_temperature",
        "name": "temperature",
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    {
        "translation_key": "opt_sn",
        "name": "sn",
        "unit": None,
        "device_class": None,
        "state_class": None,
    },
    {
        "translation_key": "opt_opt_number",
        "name": "optNumber",
        "unit": None,
        "device_class": None,
        "state_class": None,
    },
    {
        "translation_key": "opt_output_voltage",
        "name": "outputVoltage",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "translation_key": "opt_input_current",
        "name": "inputCurrent",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
]
