CHARGING_PILE_SIGNALS = [
    {
        "id": 10001,
        "display_name": "FW Version",
        "translation_key": "connector_number",
        "name": "Charging Connector No.",
        "device_class": "enum",
    },
    {
        "id": 10002,
        "display_name": "HW Version",
        "translation_key": "connector_type",
        "name": "Charging Connector Type",
        "device_class": "enum",
    },
    {
        "id": 10003,
        "display_name": "Rated Power",
        "translation_key": "rated_output_power",
        "name": "Rated Output Power",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 10004,
        "display_name": "Status",
        "translation_key": "status",
        "name": "Working Status",
        "device_class": "enum",
    },
    {
        "id": 455780004,
        "display_name": "Relay Status",
        "translation_key": "relay_status",
        "name": "Output Relay Status",
        "device_class": "enum",
    },
    {
        "id": 455780005,
        "display_name": "Connector Temp",
        "translation_key": "connector_temp",
        "name": "Charging Connector Temperature",
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    {
        "id": 10032,
        "display_name": "Phase A Current",
        "translation_key": "phase_a_current",
        "name": "A Output Current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 10033,
        "display_name": "Phase C Current",
        "translation_key": "phase_c_current",
        "name": "C Output Current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 10034,
        "display_name": "Phase B Current",
        "translation_key": "phase_b_current",
        "name": "B Output Current",
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "id": 10013,
        "display_name": "Output Power",
        "translation_key": "output_power",
        "name": "Total Output Power",
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "id": 455780014,
        "display_name": "PWM Duty",
        "translation_key": "pwm_duty",
        "name": "PWM Duty Cycle",
        "unit": "%",
        "device_class": "power_factor",
        "state_class": "measurement",
    },
    {
        "id": 10023,
        "display_name": "Connector Lock",
        "translation_key": "connector_lock",
        "name": "Lock Status",
        "device_class": "enum",
    },
    {
        "id": 455780020,
        "display_name": "Working Mode",
        "translation_key": "working_mode",
        "name": "Reported Working Mode",
        "device_class": "enum",
    },
    {
        "id": 10029,
        "display_name": "Departure Time",
        "translation_key": "departure_time",
        "name": "Planned Departure Time",
        "device_class": None,
    },
    {
        "id": 10030,
        "display_name": "Planned Charge Energy",
        "translation_key": "planned_charge_energy",
        "name": "Expected Charged Energy",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total",
    },
    {
        "id": 19999,
        "display_name": "Device Status",
        "translation_key": "connection_status",
        "name": "Device connection status",
        "device_class": "enum",
    },
    {
        "id": 10036,
        "display_name": "Charging Duration (s)",
        "translation_key": "charging_duration_(s)",
        "name": "Charging Duration",
        "unit": "s",
        "device_class": "duration",
        "state_class": "total_increasing",
    },
    {
        "id": 10035,
        "display_name": "Energy Charged",
        "translation_key": "energy_charged",
        "name": "Energy Charged",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
]

CHARGER_DEVICE_SIGNALS = [
    {
        "id": 10001,
        "translation_key": "fw_version",
        "name": "Software Version",
        "device_class": "enum",
    },
    {
        "id": 10002,
        "translation_key": "hw_version",
        "name": "Hardware Version",
        "device_class": "enum",
    },
    {
        "id": 455770003,
        "display_name": "Serial Number",
        "translation_key": "serial_number",
        "name": "ESN",
        "device_class": None,
    },
    {
        "id": 10003,
        "translation_key": "rated_power",
        "name": "Rated Power",
        "unit": "kW",
        "device_class": "power",
    },
    {
        "id": 455770005,
        "display_name": "Phase A Voltage",
        "translation_key": "phase_a_voltage",
        "name": "Phase A Voltage",
        "unit": "V",
        "device_class": "voltage",
    },
    {
        "id": 455770006,
        "display_name": "Phase B Voltage",
        "translation_key": "phase_b_voltage",
        "name": "Phase B Voltage",
        "unit": "V",
        "device_class": "voltage",
    },
    {
        "id": 455770007,
        "display_name": "Phase C Voltage",
        "translation_key": "phase_c_voltage",
        "name": "Phase C Voltage",
        "unit": "V",
        "device_class": "voltage",
    },
    {
        "id": 10007,
        "display_name": "Model",
        "translation_key": "model",
        "name": "AC Charger Model",
        "device_class": "enum",
    },
    {
        "id": 10008,
        "display_name": "Total Energy",
        "translation_key": "total_energy",
        "name": "Total Energy Charged",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "id": 455770010,
        "display_name": "Charger Temp",
        "translation_key": "charger_temp",
        "name": "AC Charger Temperature",
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    {
        "id": 10010,
        "display_name": "Port Count",
        "translation_key": "port_count",
        "name": "Charging Port Quantity",
        "device_class": "enum",
    },
    {
        "id": 10012,
        "display_name": "Bluetooth Name",
        "translation_key": "bluetooth_name",
        "name": "Bluetooth name",
        "device_class": "enum",
    },
    {
        "id": 19999,
        "translation_key": "device_status",
        "name": "Device connection status",
        "device_class": "enum",
    },
]
