PLANT_SIGNALS = [
    {
        "key": "monthEnergy",
        "display_name": "Monthly Energy",
        "translation_key": "month_energy",
        "name": "Monthly Energy",
        "unit": "kWh",
        "meter_required": False,
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "cumulativeEnergy",
        "display_name": "Total Energy",
        "translation_key": "cumulative_energy",
        "name": "Total Energy",
        "unit": "kWh",
        "meter_required": False,
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "dailyIncome",
        "display_name": "Today Income",
        "translation_key": "daily_income",
        "name": "Today Income",
        "unit": "",
        "meter_required": False,
        "device_class": "monetary",
        "state_class": "total",
    },
    {
        "key": "dailyEnergy",
        "display_name": "Today Energy",
        "translation_key": "daily_energy",
        "name": "Today Energy",
        "unit": "kWh",
        "meter_required": False,
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "yearEnergy",
        "display_name": "Yearly Energy",
        "translation_key": "year_energy",
        "name": "Yearly Energy",
        "unit": "kWh",
        "meter_required": False,
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "totalSelfUseEnergy",
        "display_name": "Self Used Energy Today",
        "translation_key": "total_self_use_energy",
        "name": "Self Used Energy Today",
        "unit": "kWh",
        "meter_required": True,
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "dailyUseEnergy",
        "display_name": "Consumption Today",
        "translation_key": "daily_use_energy",
        "name": "Consumption Today",
        "unit": "kWh",
        "meter_required": True,
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "pvSelfConsumptionEnergy",
        "display_name": "PV Self Consumption",
        "translation_key": "pv_self_consumption_energy",
        "name": "PV Self Consumption",
        "unit": "kWh",
        "meter_required": True,
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "totalFeedInEnergy",
        "display_name": "PV Feed-In Energy",
        "translation_key": "total_feed_in_energy",
        "name": "PV Feed-In Energy",
        "unit": "kWh",
        "meter_required": True,
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "totalGridImportEnergy",
        "display_name": "Imported Grid Energy",
        "translation_key": "total_grid_import_energy",
        "name": "Imported Grid Energy",
        "unit": "kWh",
        "meter_required": True,
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "totalConsumptionEnergy",
        "display_name": "Total Consumption",
        "translation_key": "total_consumption_energy",
        "name": "Total Consumption",
        "unit": "kWh",
        "meter_required": True,
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "gridImportRatio",
        "display_name": "Grid Import Ratio",
        "translation_key": "grid_import_ratio",
        "name": "Grid Import Ratio",
        "unit": "%",
        "meter_required": True,
        "device_class": "power_factor",
        "state_class": "measurement",
    },
    {
        "key": "pvSelfConsumptionRatio",
        "display_name": "Self Consumption Ratio",
        "translation_key": "pv_self_consumption_ratio",
        "name": "Self Consumption Ratio",
        "unit": "%",
        "meter_required": True,
        "device_class": "power_factor",
        "state_class": "measurement",
    },
    {
        "key": "pvSelfConsumptionRatioByProduction",
        "display_name": "Self Consumption Ratio (by PV production)",
        "translation_key": "pv_self_consumption_ratio_by_production",
        "name": "Self Consumption Ratio (by PV production)",
        "unit": "%",
        "meter_required": True,
        "device_class": "power_factor",
        "state_class": "measurement",
    },
    {
        "key": "flow_solar_power",
        "display_name": "Flow Solar Power",
        "translation_key": "flow_solar_power",
        "name": "Flow Solar Power",
        "unit": "kW",
        "meter_required": False,
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "key": "flow_battery_power",
        "display_name": "Flow Battery Power",
        "translation_key": "flow_battery_power",
        "name": "Flow Battery Power",
        "unit": "kW",
        "meter_required": False,
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "key": "flow_load_power",
        "display_name": "Flow Load Power",
        "translation_key": "flow_load_power",
        "name": "Flow Load Power",
        "unit": "kW",
        "meter_required": False,
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "key": "flow_grid_power",
        "display_name": "Flow Grid Power",
        "translation_key": "flow_grid_power",
        "name": "Flow Grid Power",
        "unit": "kW",
        "meter_required": False,
        "device_class": "power",
        "state_class": "measurement",
    },
]
